src/MediaBundle/Entity/Media.php
<?php

namespace MediaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Media
 *
 * @ORM\Table(name="media_news")
 * @ORM\Entity(repositoryClass="MediaBundle\Repository\MediaRepository")
 */
class Media
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    // ...

    /**
     * @Assert\NotBlank()
     * @Assert\File(mimeTypes={"image/gif","image/jpeg","image/png" },maxSize="10M")
     */
    private $file;


    /**
     * @var string
     *
     * @ORM\Column(name="titre", type="string", length=255, nullable=true)
     */
    private $titre;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255)
     */
    private $type;


    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     */
    private $date;
    /**
     * @var bool
     *
     * @ORM\Column(name="enabled", type="boolean")
     */
    private $enabled;
    public function __construct()
    {
        $this->date= new \DateTime();
        $this->enabled=false;
    }
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * Set titre
     *
     * @param string $titre
     * @return Media
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;

        return $this;
    }

    /**
     * Get titre
     *
     * @return string 
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Media
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getLink()
    {
        return "uploads/".$this->url;
    }   

    /**
     * Set type
     *
     * @param string $type
     * @return Media
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }
    /**
     * Get type
     *
     * @return string 
     */
    public function getType()
    {
        return $this->type;
    }
    public function getFile()
    {
        return $this->file;
    }
    public function setFile($file)
    {
        $this->file = $file;
        return $this;
    }
    public function upload($path)
    {
        
        $file = $this->getFile();
        // Generate a unique name for the file before saving it
        $fileName = md5(uniqid()).'.'.$file->guessExtension();
        $this->setTitre($file->getClientOriginalName());
        $this->setUrl($fileName);
        $this->setType("image");
        $file->move(
            $path,
            $fileName
        );
    }
    public  function delete($url)
    {
        if ($this->getType()=="image") {
            @unlink($url.$this->getUrl());
        } 
    }
    public function addVideo($url)
    {
        $video_id = explode("?v=", $url); // For videos like http://www.youtube.com/watch?v=...
        if (empty($video_id[1]))
            $video_id = explode("/v/", $url); // For videos like http://www.youtube.com/watch/v/..

        $video_id = explode("&", $video_id[1]); // Deleting any other params
        $video_id = $video_id[0];
        $content = file_get_contents("http://youtube.com/get_video_info?video_id=".$video_id);
        parse_str($content, $ytarr);
        if($ytarr['title']!=null){
            $this->setTitre($ytarr['title']);
        }else{}
        $this->setUrl($url);
        $this->setType("youtube");
    }
     public function getImage()
    {
        try {
            

        $video_id = @explode("?v=", $this->url); // For videos like http://www.youtube.com/watch?v=...
        if (empty($video_id[1]))
            $video_id = @explode("/v/", $url); // For videos like http://www.youtube.com/watch/v/..

        $video_id = @explode("&", $video_id[1]); // Deleting any other params
        $video_id = $video_id[0];
        } catch (Exception $e) {
            $video_id="iojzejfo";
        }
        return "http://img.youtube.com/vi/". $video_id."/hqdefault.jpg";
    }
    public function getImageL()
    {
        try {
            

        $video_id = @explode("?v=", $this->url); // For videos like http://www.youtube.com/watch?v=...
        if (empty($video_id[1]))
            $video_id = @explode("/v/", $url); // For videos like http://www.youtube.com/watch/v/..

        $video_id = @explode("&", $video_id[1]); // Deleting any other params
        $video_id = $video_id[0];
        } catch (Exception $e) {
            $video_id="iojzejfo";
        }
        return "http://img.youtube.com/vi/". $video_id."/maxresdefault.jpg";
    } 
    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Annonce
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }
    /**
     * Set enabled
     *
     * @param boolean $enabled
     * @return Article
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * Get enabled
     *
     * @return boolean 
     */
    public function getEnabled()
    {
        return $this->enabled;
    }
}

src/MediaBundle/Controller/MediaController.php
<?php

namespace MediaBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use MediaBundle\Entity\Media;
use MediaBundle\Entity\Gallery;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class MediaController extends Controller
{
    public function indexAction(Request $request)
    {	
        $em=$this->getDoctrine()->getManager();
        $medias=$em->getRepository("MediaBundle:Media")->findBy(array("enabled"=>false));
            

        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $medias, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            8/*limit per page*/
        );
        return $this->render('MediaBundle:Media:index.html.twig',array(
            'pagination' => $pagination,
        ));
    }
    public function deleteAction($id,Request $request){
    	$em=$this->getDoctrine()->getManager();
    	$media = $em->getRepository("MediaBundle:Media")->find($id);
    	if($media==null){
    		return $this->redirect($this->generateUrl('media_index'));
    	}
    	var_dump($media);
    	$form=$this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->add('oui', 'submit')
            ->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
 			$media->delete($this->container->getParameter('files_directory'));
        	$em->remove($media);
			$em->flush();
        	return $this->redirect($this->generateUrl('media_index'));
    	}
    	return $this->render('MediaBundle:Media:delete.html.twig',array("form"=>$form->createView()));

    }

    public function addAction(Request $request)
    {

        $media= new Media();
        $form=$this->createFormBuilder($media)
                   ->add("file")
                   ->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em=$this->getDoctrine()->getManager();
            $media->upload($this->container->getParameter('files_directory'));
            $em->persist($media);
            $em->flush();
            #return $this->redirect($this->generateUrl('media_index'));
        }
       return $this->render("MediaBundle:Media:add.html.twig",array("form"=>$form->createView(),"media"=>$media)
        
        );
    }
    public function api_uploadAction(Request $request,$token)
    {
        if ($token!=$this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");  
        }
        $code="200";
        $message="madkhlach";
        $errors=array();
        if ($this->getRequest()->files->has('uploaded_file')) {
            $message="dkhal";
            $media= new Media();
            $em=$this->getDoctrine()->getManager();

            $media->setFile($this->getRequest()->files->get('uploaded_file'));
            $media->upload($this->container->getParameter('files_directory'));
            $em->persist($media);
            $em->flush();
            $imagineCacheManager = $this->get('liip_imagine.cache.manager');
            $errors[]=array("name"=>"id","value"=>$media->getId());
            $errors[]=array("name"=>"url","value"=>$imagineCacheManager->getBrowserPath($media->getLink(), 'article_thumb'));

        }
        $error=array(
            "code"=>$code,
            "message"=>$message,
            "values"=>$errors
            );
        $encoders = array(new XmlEncoder(), new JsonEncoder());
        $normalizers = array(new ObjectNormalizer());
        $serializer = new Serializer($normalizers, $encoders);
        $jsonContent=$serializer->serialize($error, 'json');
        return new Response($jsonContent);
    }
        public function api_deleteAction(Request $request,$id,$token)
    {
        if ($token!=$this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");  
        }
        $code="200";
        $message="le fichier a ete supprimé";
        $errors=array();
        $em=$this->getDoctrine()->getManager();
        $media = $em->getRepository("MediaBundle:Media")->find($id);
        if($media==null){
            $code="404";
            $message="Le fichier n'existe pas sur nos serveur"; 
        }else{
            $media->delete($this->container->getParameter('files_directory'));
            $em->remove($media);
            $em->flush();
        }
        $error=array(
            "code"=>$code,
            "message"=>$message,
            "values"=>$errors
            );
        $encoders = array(new XmlEncoder(), new JsonEncoder());
        $normalizers = array(new ObjectNormalizer());
        $serializer = new Serializer($normalizers, $encoders);
        $jsonContent=$serializer->serialize($error, 'json');
        return new Response($jsonContent);
    }

}

src/MediaBundle/Resources/views/Media/add.html.twig
{% extends 'MediaBundle::layout.html.twig' %}
{% block body %}
	{% if media.id !=null %}
		<script type="text/javascript">
		sendToParent("{{asset(media.link)|imagine_filter('media_article')}}");
		window.close();
		</script>
	{% endif %}
	<div class="notif" >
		<div class="notif-head">
			<a href="{{path("media_index",{CKEditor:app.request.query.get("CKEditor"),CKEditorFuncNum:app.request.query.get("CKEditorFuncNum"),langCode:app.request.query.get("langCode")})}}" class="notif-close"><i class="fa fa-chevron-left" aria-hidden="true"></i>Images list</a>
			<span class="notif-title">Add image</span>
		</div>
		{{ form_start(form)}}
		
		<div class="notif-body clearfix" dir="rtl">
			<div class="thumb img-thumbnail upload" onclick="document.getElementById('form_file').click()">
				<img>
				<div class="select"> Click to add image to article <br>	 <i class="fa fa-camera fa-5x" aria-hidden="true"></i></div>
				{{form_widget(form.file,{"attr":{"style":"opacity:0;"}})}}
			</div>
			<div class="errors-form">
				{{form_errors(form.file)}}
			</div>
			<br>
			<button class="btn btn-hiya" style="width:300px;" >Upload image<i class="fa fa-send" aria-hidden="true"></i></button>
			{{form_end(form)}}
		</div>
	</div>
{% endblock %}

src/MediaBundle/Resources/views/Media/delete.html.twig
{% extends 'MediaBundle::layout.html.twig' %}
{% block body %}
	<div class="notif">
		<div class="notif-head">
			<span class="notif-close"><i class="fa fa-plus" aria-hidden="true"></i>  اظافة صورة جديدية</span>
			<span class="notif-title">قاءمة الصورة الخاصة بك</span>
		</div>
		<div class="notif-body clearfix">
			{% for media in medias %}
				<div class="thumb img-thumbnail ">
					<img  src="{{media.link|imagine_filter('media_thumb')}}">
					<div>{{media.titre}}</div>
					<div class="select"> اظافة الصورة  للمقال <i class="fa fa-plus" aria-hidden="true"></i></div>
				</div>
			{% else %}
			لا توجد لذيك اي صورة حاليا اظغطي على زر "اظاف صورة" اعلاه لاظافة صور جديدة
			{% endfor %}
		</div>
	</div>
{% endblock %}

src/MediaBundle/Resources/views/Media/index.html.twig
{% extends 'MediaBundle::layout.html.twig' %}
{% block body %}
	<div class="notif">
		<div class="notif-head">
			<a href="{{path("media_add",{CKEditor:app.request.query.get("CKEditor"),CKEditorFuncNum:app.request.query.get("CKEditorFuncNum"),langCode:app.request.query.get("langCode")})}}" class="notif-close"><i class="fa fa-plus" aria-hidden="true"></i>Add image</a>
			<span class="notif-title">Images List</span>
		</div>
		<div class="notif-body clearfix">
			{% for media in pagination %}
				<div class="thumb img-thumbnail">
					<img  src="{{media.link|imagine_filter('media_thumb')}}">
					<div>{{media.titre}}</div>
					<div class="select"  onclick='sendToParent("{{media.link|imagine_filter('media_article')}}");window.close();'> Insert Image <i class="fa fa-plus" aria-hidden="true"></i></div>
				</div>
			{% else %}
			Images list is empty "Add new image" to insert image
			{% endfor %}
		</div>
		<div>
			{{ knp_pagination_render(pagination) }}
		</div>
	</div>

{% endblock %}